<#assign liferay_ui=JspTaglibs["/WEB-INF/tld/liferay-ui.tld"] />

<#assign app_view_display_style=liferay_ui["app-view-display-style"] >			<#-- new in lp6.2 -->
<#assign app_view_entry=liferay_ui["app-view-entry"] >				<#-- new in lp6.2 -->
<#assign app_view_navigation_entry=liferay_ui["app-view-navigation-entry"] >			<#-- new in lp6.2 -->
<#assign app_view_toolbar=liferay_ui["app-view-toolbar"] >			<#-- new in lp6.2 -->
<#assign app_view_search_entry=liferay_ui["app-view-search-entry"] >			<#-- new in lp6.2 -->

<#assign asset_categories_error=liferay_ui["asset-categories-error"] >
<#assign asset_categories_navigation=liferay_ui["asset-categories-navigation"] >
<#assign asset_categories_selector=liferay_ui["asset-categories-selector"] >
<#assign asset_categories_summary=liferay_ui["asset-categories-summary"] >
<#assign asset_links=liferay_ui["asset-links"] >
<#assign asset_tags_error=liferay_ui["asset-tags-error"] >
<#assign asset_tags_navigation=liferay_ui["asset-tags-navigation"] >
<#assign asset_tags_selector=liferay_ui["asset-tags-selector"] >
<#assign asset_tags_summary=liferay_ui["asset-tags-summary"] >

<#assign breadcrumb=liferay_ui.breadcrumb >
<#assign calendar=liferay_ui.calendar >
<#assign captcha=liferay_ui.captcha >
<#assign categorization_filter=liferay_ui["categorization-filter"] >			<#-- new in lp6.2 -->
<#assign custom_attribute=liferay_ui["custom-attribute"] >
<#assign custom_attribute_list=liferay_ui["custom-attribute-list"] >
<#assign custom_attributes_available=liferay_ui["custom-attributes-available"] >
<#assign ddm_template_selector=liferay_ui["ddm-template-selector"] >			<#-- new in lp6.2 -->
<#assign diff=liferay_ui.diff >
<#assign diff_html=liferay_ui["diff-html"] >
<#assign discussion=liferay_ui.discussion >
<#assign error=liferay_ui.error >
<#assign error_marker=liferay_ui["error-marker"] >
<#assign flags=liferay_ui.flags >
<#assign flash=liferay_ui.flash >
<#assign form_navigator=liferay_ui["form-navigator"] >

<#assign group_search=liferay_ui["group-search"] >
<#assign header=liferay_ui["header"] >
<#assign icon=liferay_ui.icon >
<#assign icon_deactivate=liferay_ui["icon-deactivate"] >
<#assign icon_delete=liferay_ui["icon-delete"] >
<#assign icon_help=liferay_ui["icon-help"] >
<#assign icon_list=liferay_ui["icon-list"] >
<#assign icon_menu=liferay_ui["icon-menu"] >

<#assign input_asset_links=liferay_ui["input-asset-links"] >
<#assign input_checkbox=liferay_ui["input-checkbox"] >
<#assign input_date=liferay_ui["input-date"] >
<#assign input_editor=liferay_ui["input-editor"] >
<#assign input_field=liferay_ui["input-field"] >
<#assign input_localized=liferay_ui["input-localized"] >
<#assign input_move_boxes=liferay_ui["input-move-boxes"] >
<#assign input_permissions=liferay_ui["input-permissions"] >
<#assign input_permissions_params=liferay_ui["input-permissions-params"] >
<#assign input_repeat=liferay_ui["input-repeat"] >
<#assign input_resource=liferay_ui["input-resource"] >
<#assign input_scheduler=liferay_ui["input-scheduler"] >
<#assign input_search=liferay_ui["input-search"] >			<#-- new in lp6.2 -->
<#assign input_select=liferay_ui["input-select"] >
<#assign input_textarea=liferay_ui["input-textarea"] >
<#assign input_time=liferay_ui["input-time"] >
<#assign input_time_zone=liferay_ui["input-time-zone"] >

<#assign journal_article=liferay_ui["journal-article"] >
<#assign journal_content_search=liferay_ui["journal-content-search"] >
<#assign language=liferay_ui.language >
<#assign logo_selector=liferay_ui["logo-selector"] >
<#assign membership_policy_error=liferay_ui["membership-policy-error"] >			<#-- new in lp6.2 -->
<#assign message=liferay_ui.message >
<#assign my_sites=liferay_ui["my-sites"] >
<#assign navigation=liferay_ui["navigation"] >
<#assign page_iterator=liferay_ui["page-iterator"] >
<#assign panel=liferay_ui.panel >
<#assign panel_container=liferay_ui["panel-container"] >
<#-- <#assign panel_floating_container=liferay_ui["panel-floating-container"] >  -->
<#assign param=liferay_ui["param"] >
<#assign png_image=liferay_ui["png-image"] >
<#assign progress=liferay_ui.progress >		<#-- new in lp6.2 -->
<#assign ratings=liferay_ui.ratings >
<#assign ratings_score=liferay_ui["ratings-score"] >
<#assign restore_entry=liferay_ui["restore-entry"] >			<#-- new in lp6.2 -->
<#assign rss=liferay_ui.rss >			<#-- new in lp6.2 -->
<#assign rss_settings=liferay_ui["rss-settings"] >			<#-- new in lp6.2 -->


<#assign search=liferay_ui["search"] >
<#assign search_container=liferay_ui["search-container"] >
<#assign search_container_column_button=liferay_ui["search-container-column-button"] >
<#assign search_container_column_date=liferay_ui["search-container-column-date"] >			<#-- new in lp6.2 -->
<#assign search_container_column_jsp=liferay_ui["search-container-column-jsp"] >
<#assign search_container_column_status=liferay_ui["search-container-column-status"] >			<#-- new in lp6.2 -->
<#assign search_container_column_text=liferay_ui["search-container-column-text"] >
<#assign search_container_results=liferay_ui["search-container-results"] >
<#assign search_container_row=liferay_ui["search-container-row"] >
<#assign search_container_row_parameter=liferay_ui["search-container-row-parameter"] >
<#assign search_form=liferay_ui["search-form"] >
<#assign search_iterator=liferay_ui["search-iterator"] >
<#assign search_paginator=liferay_ui["search-paginator"] >
<#assign search_speed=liferay_ui["search-speed"] >
<#assign search_toggle=liferay_ui["search-toggle"] >

<#assign section=liferay_ui.section >
<#assign sites_directory=liferay_ui["sites-directory"] >			<#-- new in lp6.2 -->

<#assign social_activities=liferay_ui["social-activities"] >
<#assign social_bookmark=liferay_ui["social-bookmark"] >
<#assign social_bookmarks=liferay_ui["social-bookmarks"] >
<#assign staging=liferay_ui.staging >
<#assign success=liferay_ui.success >
<#assign table_iterator=liferay_ui["table-iterator"] >
<#assign tabs=liferay_ui.tabs >
<#assign toggle=liferay_ui.toggle >
<#assign toggle_area=liferay_ui["toggle-area"] >
<#assign toggle_value=liferay_ui["toggle-value"] >
<#assign trash_empty=liferay_ui["trash-empty"] >			<#-- new in lp6.2 -->
<#assign trash_undo=liferay_ui["trash-undo"] >			<#-- new in lp6.2 -->
<#assign upload_progress=liferay_ui["upload-progress"] >
<#assign user_display=liferay_ui["user-display"] >
<#assign user_search=liferay_ui["user-search"] >
<#assign webdav=liferay_ui["webdav"] >
<#assign write=liferay_ui["write"] >
